model:
  category: "category"
  category_path: "out/model_100_10_1e-06_conf-1-category/epoch_21.pth" # In case that the category model is pretrained.
  joint: true # joint training. The category path above is ignored.
  scoring: "scoring_joint"
  input_dim: 128
  out_dim: 128
  num_layers: 3
  num_classes: 6 # number of category classes
  dropout_rate: 0.5
  is_norm: false
  num_cms: 2
  cms: ['aasist_ssl', 'vocosig']
loss:
  name: "Loss_category_class_CE"
  lambda_cate: 0.5
  lambda_class: 0.5
data:
  name: "data_utils_noise"
  score_path: "scores/nov22_supcon_nov22"
  audio_dir: "DATA/supcon_nov22"

